product 서비스 추가

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -14,6 +14,7 @@ jobs:
     outputs:
       gateway_service_deploy: ${{ steps.check-deploy-label.outputs.gateway_service_deploy }}
       member_service_deploy: ${{ steps.check-deploy-label.outputs.member_service_deploy }}
+      product_service_deploy: ${{ steps.check-deploy-label.outputs.product_service_deploy }}
     steps:
       - name: Check deploy label
         id: check-deploy-label
@@ -31,6 +32,9 @@ jobs:
             
             const hasMemberServiceDeployLabel = pr.data.labels.map(label => label.name).includes("member-service-deploy");
             core.setOutput("member_service_deploy", hasMemberServiceDeployLabel ? "true" : "false");
+            
+            const hasProductServiceDeployLabel = pr.data.labels.map(label => label.name).includes("product-service-deploy");
+            core.setOutput("product_service_deploy", hasProductServiceDeployLabel ? "true" : "false");
 
       - name: Explain deploy decision
         run: |
@@ -46,6 +50,13 @@ jobs:
             echo "🚚 member-service 배포 작업을 진행합니다."
           else
             echo "✋ member-service 배포 작업을 진행하지 않습니다."
+          fi
+          
+          # product-service 배포 여부 체크
+          if [[ "${{ steps.check-deploy-label.outputs.product_service_deploy }}" == "true" ]]; then
+            echo "🚚 product-service 배포 작업을 진행합니다."
+          else
+            echo "✋ product-service 배포 작업을 진행하지 않습니다."
           fi
 
   gateway-service-image-build:
@@ -152,6 +163,58 @@ jobs:
           echo "member_service_image_build_result=success" >> $GITHUB_OUTPUT
           fi
 
+  product-service-image-build:
+    needs: [ check-deploy-condition ]
+    if: needs.check-deploy-condition.outputs.product_service_deploy == 'true'
+    runs-on: ubuntu-latest
+    permissions:
+      id-token: write
+      contents: read
+    outputs:
+      product_service_image_build_result: ${{ steps.image-build-result.outputs.product_service_image_build_result }}
+    continue-on-error: true
+    steps:
+      - name: Checkout the code
+        uses: actions/checkout@v4
+
+      - name: Set up jdk
+        uses: actions/setup-java@v4
+        with:
+          java-version: '21'
+          distribution: 'corretto'
+
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v3
+
+      - name: Grant execute permission for gradlew
+        run: chmod +x gradlew\
+
+      - name: Build with gradle
+        run: ./gradlew :product-service:bootJar -Pspring.profiles.active=prod --info
+
+      - name: Login to Github Container Registry
+        uses: docker/login-action@v3.2.0
+        with:
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GHCR_TOKEN }}
+
+      - name: Docker build & push
+        id: docker-build-and-push
+        working-directory: ./product-service
+        run: |
+          docker build --no-cache -f docker/Dockerfile --build-arg SPRINGBOOT_APP_PROFILE=prod --platform linux/amd64 -t ${{ secrets.PRODUCT_SERVICE_GHCR_IMAGE }}:${{ github.sha }} .
+          docker push ${{ secrets.PRODUCT_SERVICE_GHCR_IMAGE }}:${{ github.sha }}
+
+      - name: Set Image build result
+        if: always()
+        id: image-build-result
+        run: |
+          echo "product_service_image_build_result=fail" >> $GITHUB_OUTPUT
+          if [[ ${{ steps.docker-build-and-push.outcome }} == "success" ]]; then
+          echo "product_service_image_build_result=success" >> $GITHUB_OUTPUT
+          fi
+
   gateway-service-deploy:
     needs: [ gateway-service-image-build ]
     if: needs.gateway-service-image-build.outputs.gateway_service_image_build_result == 'success'
@@ -197,6 +260,9 @@ jobs:
 
           if [ ! -f .member-service-secret ]; then
             touch .member-service-secret
+          
+          if [ ! -f .product-service-secret ]; then
+            touch .product-service-secret
           fi
 
       - name: Start new server application
@@ -263,6 +329,9 @@ jobs:
 
           if [ ! -f .gateway-service-secret ]; then
             touch .gateway-service-secret
+          
+          if [ ! -f .product-service-secret ]; then
+            touch .product-service-secret
           fi
 
       - name: Start new server application
@@ -287,15 +356,86 @@ jobs:
           echo "❌ member-service가 60초 동안 정상 실행되지 않음..."
           exit 1
 
+  product-service-deploy:
+    needs: [ product-service-image-build ]
+    if: needs.product-service-image-build.outputs.product_service_image_build_result == 'success'
+    runs-on: groovid-app-ec2-runner
+    continue-on-error: true
+    outputs:
+      product_service_deploy_result: ${{ steps.deploy-result.outputs.product_service_deploy_result }}
+    steps:
+      - name: Checkout the code
+        uses: actions/checkout@v4
+
+      - name: Login to Github Container Registry
+        uses: docker/login-action@v3.2.0
+        with:
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GHCR_TOKEN }}
+
+      - name: Create secret file
+        run: |
+          cd ~/project
+          
+          cat <<EOF > .env
+          MEMBER_SERVICE_IMAGE_REPOSITORY=${{ secrets.MEMBER_SERVICE_GHCR_IMAGE }}
+          MEMBER_SERVICE_IMAGE_TAG=${{ github.sha }}
+          
+          GATEWAY_SERVICE_IMAGE_REPOSITORY=${{ secrets.GATEWAY_SERVICE_GHCR_IMAGE }}
+          GATEWAY_SERVICE_IMAGE_TAG=${{ github.sha }}
+          EOF
+          
+          cat <<EOF > .product-service-secret
+          PORT_NUMBER=8084
+          DB_URL=${{ secrets.DB_URL }}
+          DB_USER_NAME=${{ secrets.DB_USER_NAME }}
+          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
+          
+          KAFKA_BOOTSTRAP_SERVERS=${{ secrets.KAFKA_BOOTSTRAP_SERVERS }}
+          AUCTION_SERVICE_BASE_URL=${{ secrets.AUCTION_SERVICE_BASE_URL }}
+          EOF
+
+          if [ ! -f .gateway-service-secret ]; then
+            touch .gateway-service-secret
+          
+          if [ ! -f .member-service-secret ]; then
+            touch .member-service-secret
+          fi
+
+      - name: Start new server application
+        id: start-new-server-application
+        run: |
+          cd ~/project
+          sudo docker-compose stop product-service
+          sudo docker-compose rm -f product-service
+          sudo docker-compose up -d product-service
+          
+          echo "🔍 product-service 헬스 체크 확인 중..."
+          for i in {1..20}; do
+            response=$(curl -s http://localhost:8084/product-service/actuator/health || true)
+            if [[ "$response" == *'"status":"UP"'* ]]; then
+              echo "🍺 product-service 정상 실행 확인!"
+              exit 0
+            else
+              echo "⏳ product-service 실행 대기... ($i/20)"
+              sleep 3
+            fi
+          done
+          echo "❌ product-service가 60초 동안 정상 실행되지 않음..."
+          exit 1
+
   cleanup-secret-files:
-    needs: [ gateway-service-deploy, member-service-deploy ]
+    needs: [ gateway-service-deploy, member-service-deploy, product-service-deploy ]
     if: |
       always() &&
-      (needs.gateway-service-deploy.result != 'skipped' || needs.member-service-deploy.result != 'skipped')
+      (needs.gateway-service-deploy.result != 'skipped' 
+      || needs.member-service-deploy.result != 'skipped' 
+      || needs.product-service-deploy.result != 'skipped')
     runs-on: groovid-app-ec2-runner
     steps:
       - name: Remove secret files from EC2 host
         run: |
           cd ~/project
-          sudo rm -rf .env .gateway-service-secret .member-service-secret
+          sudo rm -rf .env .gateway-service-secret .member-service-secret .product-service-secret
           echo "🧹 민감 정보 파일(.env, secret)이 깔끔하게 정리되었습니다."
